name: Sync Wiki to Docs

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Clone Wiki repository
        run: git clone https://github.com/dldimitrov/POCs.wiki.git wiki

      - name: Sync wiki content to /docs
        run: |
          mkdir -p docs
          rsync -av --delete --exclude='.git' wiki/ docs/
          # Rename Home.md to index.md for TechDocs if exists
          if [ -f docs/Home.md ]; then mv docs/Home.md docs/index.md; fi

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --cached --quiet || git commit -m "Sync wiki content from POCs.wiki"
          git push