name: Sync Wiki to Docs

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout docs repo
        uses: actions/checkout@v4

      - name: Clone Wiki repository
        run: |
          git clone https://github.com/dldimitrov/POCs.wiki.git wiki

      - name: Sync wiki content
        run: |
          rsync -av --delete wiki/ docs/
        # This copies everything from the wiki repo to a /docs folder

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs/
          git diff --cached --quiet || git commit -m "Sync wiki content"
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}